FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3 gcc-multilib build-essential

COPY . /repo
WORKDIR /repo/tools
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /repo/tools/bin2txt/bin2txt /
